### ISSUE TITLE
TS2769: No overload matches this call on draft

### ISSUE THREAD

**Issue by efstathiosntonas** [unadlib/mutative#1]
Hi, thank you for this lib. I'm already using immer and wanted to try mutative out. 

After replacing `produce` with `create` typescript is complaining (with immer I had no issues).

```bash
TS2769: No overload matches this call.   The last overload gave the following error.  
   Type '(draft: { [key: string]: { file_name: string; state: string; type: string; uri: string; }; }) => void' has no properties in common with type 'Options<false, false>'.
```

![Screenshot 2023-01-02 at 12 28 30](https://user-images.githubusercontent.com/717975/210219467-2cabe7d9-7fd8-4618-8906-91af1b092e64.png)

Am I missing something? Thanks

**Comment by unadlib** [comment]
hi  @efstathiosntonas , Mutative and Immer have different type inference modes, and you do not need to specify the type in the draft. It will automatically inference the draft type from the base state.

You only need to do this.

```ts
const state = create(base as { [key: string]: {...} }, (draft) => {
  //
});
```

**Comment by efstathiosntonas** [comment]
@unadlib, thanks, in the case above the ts errors went away, still facing the same error in a different scenario:  

![Screenshot 2023-01-02 at 12 55 54](https://user-images.githubusercontent.com/717975/210222262-88f8fcfc-4b4a-430c-b3f8-a6550a44c36b.png)

**Comment by unadlib** [comment]
hi @efstathiosntonas, Mutative draft functions do not support return values, you can try again.

**Comment by efstathiosntonas** [comment]
@unadlib crap, I've missed that :) . Thanks, errors went away.
