### ISSUE TITLE
Doesn't react-native support proxy in 0.64?

### ISSUE THREAD

**Issue by ModyQyW** [unadlib/mutative#2]
In README: 

> Migration is also not possible for React Native which does not support Proxy.

Doesn't react-native support proxy in 0.64? See <https://reactnative.dev/blog/2021/03/12/version-0.64#hermes-with-proxy-support>.

**Comment by unadlib** [comment]
I am sorry for my lack of detail. React Native uses a new JS engine during refactoring - Hermes, and it (if < v0.59 or when using the Hermes engine on React Native < v0.64) [does not support Proxy on Android](https://github.com/facebook/hermes/issues/33), but like you mentioned, the latest version of Hermes already supports it.

**Comment by ModyQyW** [comment]
I think better to update README and clarify it.
