### ISSUE TITLE
[Question] behavior with symbol keys

### ISSUE THREAD

**Issue by exuanbo** [unadlib/mutative#25]
Thank you for creating this awesome project! I have been working on a library that implements the full `immer` API using `mutative` under the hood (why not :smile:) and I noticed some differences. I'm not sure if this is intended or not. If you think this is a bug, I'm happy to create a PR to fix it.

```ts
import { create } from 'mutative';

test('object with Symbol key at root', () => {
  const a = Symbol('a');
  const data: Record<PropertyKey, any> = {
    [a]: 'str',
  };

  const state = create(data, (draft) => {
    expect(draft[a]).toBe('str');
    draft.foobar = 'str';
  });
  expect(state).toEqual({
    [a]: 'str',
    foobar: 'str',
  });
});
```

StackBlitz: <https://stackblitz.com/edit/vitest-dev-vitest-4fcbnc?file=test%2Fcreate.test.ts>

This will fail with:

```diff
- Expected
+ Received

  Object {
    "foobar": "str",
-   Symbol(a): "str",
  }
```

The symbol key is not copied from the original object.

And I also found this test case:

https://github.com/unadlib/mutative/blob/5e567cde57f869c79dc672917d155914be43edbb/test/immer/__tests__/base.ts#L908-L921

**Comment by unadlib** [comment]
hi @exuanbo , initially, I designed it this way intentionally. In the default configuration, Mutative is aimed at achieving ultimate performance, so it should be as such. However, I think that the difference in behavior between triggering/using a shallow copy and merely getting a value is a bug.

```ts
const state = create(data, (draft) => {
  expect(draft[a]).toBe('str'); // Shallow copy is not used
  draft.foobar = 'str';
});
```

```ts
const state = create(data, (draft) => {
    draft.foobar = 'str'; //  Shallow copy is used
  expect(draft[a]).not.toBe('str'); //  it's `undefined`
});
```

I'm pleased that you've raised this issue. Upon rethinking this behavior, I think it should align with the behavior of a spread object, prioritizing alignment with the spread object's behavior over performance improvement..

I look forward to your PR. If you're quite busy, I might fix this issue in two days and release a new version.

> I would like to add that after fixing this behavior, the performance of mutative will decrease from the original 2x that of the spread object to 1.4x.

**Comment by exuanbo** [comment]
Hi @unadlib, I just published the library <https://github.com/exuanbo/mutative-compat>

It would be nice to have it mentioned in the Mutative documentation if you find it suitable 😀. Anyway, thanks again!

**Comment by unadlib** [comment]
Sure, I'd be more than happy to mention [mutative-compat](https://github.com/exuanbo/mutative-compat) in Mutative docs. It will greatly help users migrate from Immer to Mutative.
