### ISSUE TITLE
Proposal: support in-place updates of original mutable state

### ISSUE THREAD

**Issue by zygfryd** [unadlib/mutative#33]
I stumbled upon this library because I was looking for something to do transactional updates to a mutable object tree, and sadly couldn't find anything.

The idea is simple, I have some mutable state that's deeply referenced throughout a piece of code. Now I want to run a DSL script on the state, but I don't trust the script to run to completion every time. So I want to buffer any updates to my state until it finishes running without crashing or being aborted by the user, and then commit the changes to my state without making a copy and having to update all references to it.

The API could be a mirror set of functions, eg. `produceInPlace`, `finalizeInPlace`, `applyInPlace`.

Making sure the state isn't mutated from outside while a transaction is running is the caller's responsibility.

Hope that makes sense.

**Comment by unadlib** [comment]
hi @zygfryd , this idea is good, but it's not suitable for implementation within the Mutative lib. 

I will soon create a new lib for this proposal.

**Comment by unadlib** [comment]
I just released `mutability v0.1.1` based on Mutative. Feel free to use it, and if you have any questions, please don't hesitate to contact me.

https://github.com/unadlib/mutability

**Comment by zygfryd** [comment]
Thanks, I'll check it out.
