### ISSUE TITLE
Ability to make Strict Mode the default

### ISSUE THREAD

**Issue by rynti** [unadlib/mutative#43]
Hey there, I hope this is an okay place to ask this question.

I was wondering if there was any way to by default enable strict mode globally? I'd like to enable strict mode by default in a development build, and turn it off for production, but haven't found an ergonomic way to do that.

In your docs this is also [the recommended way](https://mutative.js.org/docs/advanced-guides/strict-mode#strict-mode-options):
<img width="971" alt="image" src="https://github.com/unadlib/mutative/assets/918675/dce8e9d7-9d9f-4b45-b2af-3043f6b1778f">

Would love to hear suggestions for users of this library on how they would go about doing that.

Thanks in advance!

**Comment by unadlib** [comment]
hi @rynti , you can use `strict: process.env.NODE_ENV !== 'production'` to enable strict mode by default in a development build.

For example,

```ts
create(
  { count: 0 },
  (draft) => {
    //
  },
  {
    strict: process.env.NODE_ENV !== "production",
  }
);
```
