### ISSUE TITLE
Draft's don't detect deconstred variable reassignment.

### ISSUE THREAD

**Issue by BjornHMS** [unadlib/mutative#53]
```typescript
const myState = { A: { a: 1, aa: 2 }, B: { b: 1, bb: 2 }};

// this works
const newState = create(myState, (({ A }) => { A.a = 3; }) 

// this does not
const newState = create(myState, (({ A: { a } }) => { a = 3; }) 
// neither does this
const newState = create(myState, (({ A }) => { 
    let { a } = A;  
    a = 3; 
}) 
```

I'm guessing the issue is that the deconstructed variables just point to the actual state properties.
So when I do A.a .. I'm getting the actual variable in the state.
But when I deconstruct A to get a .. I get a variable that points to the a variable, so when I try to reassign it, I'm just reassigning the pointer variable.

I don't know if there is a proper solution to this, other then some fuckery with Proxy where you detect reassignments and under the hood change the correct variable.

**sidenote:** 
in the examples that don't work, eslint complains that the variable is assigned a value but never used.

**Comment by unadlib** [comment]
Your guess is correct, there is a fundamental difference between variable assignment and setting a property on an object. In JavaScript, variable assignment cannot be intercepted or proxied.

**Comment by BjornHMS** [comment]
For shits and giggles I wrote my own solution that let you proxy primitives via a state proxy.
And found out quickly why that is a bad idea.

```typescript
const myState = { a: true, b: false };

const newState = proxyState(myState, (({ a, b }) => {
 a = !a; 
 b = !b;
 });
 ```
 since a and b are proxies aka objects, this '!proxy' would always be false

**Comment by BjornHMS** [comment]
Obviously "fixing" this would break other behavior .. and it's wholly unnecessary
I did enjoy the puzzle though... closing.
