### ISSUE TITLE
how does mutative compare with immutable-js?

### ISSUE THREAD

**Issue by iambumblehead** [unadlib/mutative#56]
how does mutative compare with [immutable-js?](https://www.npmjs.com/package/immutable)

both packages have roughly the same install size and 0 dependencies

https://packagephobia.com/result?p=immutable
https://packagephobia.com/result?p=mutative

**Comment by unadlib** [comment]
## Immutable.js vs Mutative 

### Data Structures and API

#### Immutable.js
- Provides its own set of immutable data structures (Map, List, Set, etc.)
- Has a completely new API to learn and use
- Requires converting to and from plain JavaScript objects

####  Mutative
- Works with plain JavaScript objects and arrays
- Uses a more familiar API based on normal JavaScript operations
- `No need to convert data structures`

### Bundle Size

#### Immutable.js
- Larger bundle size (around 17.7KB minified and gzipped)
https://bundlephobia.com/package/immutable@4.3.7

#### Mutative
- Smaller bundle size (around 6.8KB minified and gzipped)
https://bundlephobia.com/package/mutative@1.0.8

`Mutative is nearly 3X smaller than Immutable.js.`

### Performance

```
Mutative - No Freeze x 5,740 ops/sec ±0.75% (98 runs sampled)
Naive handcrafted reducer - No Freeze x 3,786 ops/sec ±0.32% (98 runs sampled)
Immutable.js - No Freeze x 201 ops/sec ±4.02% (87 runs sampled)
```

With a simple performance comparison, `Mutative is 28X faster than Immutable.js` (maybe a full benchmark performance test if necessary)

**Comment by iambumblehead** [comment]
thank you for a thorough answer

**Comment by iambumblehead** [comment]
This benchmark can be used with node's official [benchmark.js scripts](https://github.com/nodejs/node/blob/main/doc/contributing/writing-and-running-benchmarks.md#basics-of-a-benchmark) **The last number is the rate of operations measured in ops/sec (higher is better).**

_note: node's common.js benchmark file uses one or two commonjs-specific things and those must be updated before the benchmark will run successfully_

<details>
  <summary>immutable-vs-mutative-benchmark.js</summary>

```javascript
import common from '../node-v22.9.0/benchmark/common.js'
import { Map as ImmutableMap } from 'immutable'
import { create } from 'mutative'

const TYPESIMPLEIMMUTABLE = 'map set (simple), immutable'
const TYPESIMPLEMUTATIVE = 'map set (simple),  mutative'
const TYPESIMPLEJSSPREAD = 'map set (simple), js spread'

const bench = common.createBenchmark(main, {
  n: [1400],
  mod: 0,
  type: [
    TYPESIMPLEIMMUTABLE,
    TYPESIMPLEMUTATIVE,
    TYPESIMPLEJSSPREAD
  ]
})

async function main(conf) {
  // save then return this obj to try bypassing any
  // runtime optimisation identifying this code as unused
  let obj = Math.random()

  const type = conf.type
  const mod = conf.mod

  if (type === TYPESIMPLEIMMUTABLE) {
    bench.start()

    obj = ImmutableMap()
    for (let i = conf.n; i--;) {
      const key = 'key'+ (mod ? i % mod : i)
      const value = 'value'+i
      obj = obj.set(key, {key, value})
    }

    bench.end(conf.n)
  }

  if (type === TYPESIMPLEMUTATIVE) {
    bench.start()
    obj = {}
    for (let i = conf.n; i--;) {
      const key = 'key'+ (mod ? i % mod : i)
      const value = 'value'+i

      obj = create(obj, draft => { draft[key] = {key, value} })
    }
    bench.end(conf.n)
  }  

  if (type === TYPESIMPLEJSSPREAD) {
    bench.start()
    obj = {}
    for (let i = conf.n; i--;) {
      const key = 'key'+ (mod ? i % mod : i)
      const value = 'value'+i
      obj = {...obj, [key]: {key, value}}
    }
    bench.end(conf.n)
  }

  return obj
}
```
</details>

```bash
.js type="map set (simple), immutable" mod=0 n=1400: 182,321.69751918773
.js type="map set (simple),  mutative" mod=0 n=1400: 7,983.552422160762
.js type="map set (simple), js spread" mod=0 n=1400: 4,416.27809570669
```

Perhaps mutative is used incorrectly in the test, however, it does not appear to be as fast as immutable-js here, even when the modulo value is used to limit the size of the target objects.

**Comment by unadlib** [comment]
The main point of contention in this benchmark is whether to call `fromJS` at the beginning and `toJS` at the end in the ImmutableJS use case. This will significantly affect the benchmark results. It means that this is a test of two different data structures.

In a real use case, this usually implies issues such as data persistence and serialization, among others. Therefore, it's not appropriate to simply compare the update part without considering the cost of data transformation.

Nevertheless, I appreciate the benchmark you provided.

**Comment by iambumblehead** [comment]
when `.toJS()` is added to each loop iteration immutable becomes the slowest, however my own applications rarely or never use `.toJS()`
```diff
bench.start()

obj = ImmutableMap()
for (let i = conf.n; i--;) {
  const key = 'key' + (mod ? i % mod : i)
- const value = 'value'
+ const value = 'value' + obj.toJS()
  obj = obj.set(key, {key, value})
}

bench.end(conf.n)
```

```bash
.js type="map set (simple), immutable" mod=0 n=1400: 2,077.274856115257
.js type="map set (simple),  mutative" mod=0 n=1400: 7,864.342253208879
.js type="map set (simple), js spread" mod=0 n=1400: 4,360.408478955066
```

**Comment by iambumblehead** [comment]
if 'toJS()' is added after the loop the completes, so that it is called a single time for each test, then the performance is similar to mutative. toJS() indeed has a significant performance impact
```bash
.js type="map set (simple), immutable" mod=0 n=1400: 108,937.36117295036
.js type="map set (simple),  mutative" mod=0 n=1400: 115,734.6937560802
.js type="map set (simple), js spread" mod=0 n=1400: 4,431.156180752305
```
