### ISSUE TITLE
[bug] Invalid patch produced from array.splice() call

### ISSUE THREAD

**Issue by davidye** [unadlib/mutative#68]
```
const x: string[] = ["a"];
const [_, patches] = create(
  x,
  (draft) => {
    draft.splice(0, 1);
  },
  { enablePatches: true }
);

console.log(patches);
```

This produces:

```[{ op: "replace", path: "length"], value: 0 }]```

When it should be a "remove" operation

**Comment by davidye** [comment]
I did see that this may be intentional from: https://github.com/unadlib/mutative/pull/65

But I think the generated patch should not include "length" for it to match the JSON patch spec? FWIW immer does handle this case with "remove".

**Comment by unadlib** [comment]
hi @davidye , by default, Mutative’s patch generation rules differ slightly from the JSON Patch spec.  The doc: https://github.com/unadlib/mutative?tab=readme-ov-file#createstate-fn-options.

You can set `arrayLengthAssignment: false` to meet your requirements.

```ts
const x: string[] = ['a'];
const [_, patches] = create(
  x,
  (draft) => {
    draft.splice(0, 1);
  },
  {
    enablePatches: {
      arrayLengthAssignment: false,
    },
  }
);

console.log(patches); // [ { op: 'remove', path: [ 0 ] } ]
```

Here https://github.com/unadlib/mutative/issues/6 is more related discussion.

**Comment by unadlib** [comment]
> >This would work. I suggest defaulting to 100% spec-compatible patches.

> I'm afraid not, arrayLengthAssignment should be true by default, otherwise most users using patches will suffer additional performance loss.

 https://github.com/unadlib/mutative/issues/6#issuecomment-1406141029

**Comment by davidye** [comment]
Oh I see, thank you! Excellent library by the way this is exactly what I was looking for.
