### ISSUE TITLE
`create` not working with custom extension of `Set` properly

### ISSUE THREAD

**Issue by farskid** [unadlib/mutative#70]
I have a custom class that extends `Set` and is used widely as a data model across the application I'm building. However, when using it with `create`, the returned draft becomes a `Set` class rather than the custom extension it was passed. Haven't looked at the source code but I'm guessing there's a `instanceof Set`  check that is correctly `true` in this case and the returned value is built off of `Set`?

Repro: https://stackblitz.com/edit/vitejs-vite-zyuqye?file=src%2Fmain.ts&terminal=dev

In the type level, it works fine. In the runtime, it converts the draft to `Set`.

**Comment by unadlib** [comment]
hi @farskid , thank you for reporting this issue. I will fix it as soon as possible. However, I’m a bit curious, as the Custom Set seems rather uncommon. I’ll need some time to carefully review the relevant logic.

**Comment by unadlib** [comment]
hi @farskid , Mutative v1.1.0 has been released, it supports custom Set and Map, and the performance of Set has been improved by more than 30%.

**Comment by unadlib** [comment]
#45

**Comment by farskid** [comment]
Awesome work! Thanks for addressing this issue.
